export const mock_data = [
  {
    id: 1,
    team_name: "Godlike",
    matches_played: 3,
    wins: 1,
    finishes: 23,
    bonus_finishes: 0,
    finish_points: 23,
    position: 1,
    position_points: 16,
  },
  {
    id: 2,
    team_name: "OR Esports",
    matches_played: 2,
    wins: 0,
    finishes: 14,
    bonus_finishes: 0,
    finish_points: 14,
    position: 2,
    position_points: 24,
  },
  {
    id: 3,
    team_name: "RNT",
    matches_played: 3,
    wins: 3,
    finishes: 3,
    bonus_finishes: 3,
    finish_points: 3,
    position: 3,
    position_points: 3,
  },
  {
    id: 4,
    team_name: "VLT",
    matches_played: 4,
    wins: 4,
    finishes: 4,
    bonus_finishes: 4,
    finish_points: 4,
    position: 4,
    position_points: 4,
  },
  {
    id: 5,
    team_name: "Soul",
    matches_played: 5,
    wins: 5,
    finishes: 5,
    bonus_finishes: 5,
    finish_points: 5,
    position: 5,
    position_points: 5,
  },
  {
    id: 6,
    team_name: "8BIT",
    matches_played: 6,
    wins: 6,
    finishes: 6,
    bonus_finishes: 6,
    finish_points: 6,
    position: 6,
    position_points: 6,
  },
  {
    id: 7,
    team_name: "Enigma",
    matches_played: 7,
    wins: 7,
    finishes: 7,
    bonus_finishes: 7,
    finish_points: 7,
    position: 7,
    position_points: 7,
  },
  {
    id: 8,
    team_name: "TX",
    matches_played: 8,
    wins: 8,
    finishes: 8,
    bonus_finishes: 8,
    finish_points: 8,
    position: 8,
    position_points: 8,
  },
  {
    id: 9,
    team_name: "BLIND",
    matches_played: 9,
    wins: 9,
    finishes: 9,
    bonus_finishes: 9,
    finish_points: 9,
    position: 9,
    position_points: 9,
  },
  {
    id: 10,
    team_name: "CHEMIN",
    matches_played: 10,
    wins: 10,
    finishes: 10,
    bonus_finishes: 10,
    finish_points: 10,
    position: 10,
    position_points: 10,
  },
  {
    id: 11,
    team_name: "GLADIATORS",
    matches_played: 11,
    wins: 11,
    finishes: 11,
    bonus_finishes: 11,
    finish_points: 11,
    position: 11,
    position_points: 11,
  },
  {
    id: 12,
    team_name: "OG",
    matches_played: 12,
    wins: 12,
    finishes: 12,
    bonus_finishes: 12,
    finish_points: 12,
    position: 12,
    position_points: 12,
  },
  {
    id: 13,
    team_name: "GLOBAL ESPORTS",
    matches_played: 13,
    wins: 13,
    finishes: 13,
    bonus_finishes: 13,
    finish_points: 13,
    position: 13,
    position_points: 13,
  },
  {
    id: 14,
    team_name: "Chad",
    matches_played: 14,
    wins: 14,
    finishes: 14,
    bonus_finishes: 14,
    finish_points: 14,
    position: 14,
    position_points: 14,
  },
  {
    id: 15,
    team_name: "Lila",
    matches_played: 15,
    wins: 15,
    finishes: 15,
    bonus_finishes: 15,
    finish_points: 15,
    position: 15,
    position_points: 15,
  },
  {
    id: 16,
    team_name: "Theodor",
    matches_played: 16,
    wins: 16,
    finishes: 16,
    bonus_finishes: 16,
    finish_points: 16,
    position: 16,
    position_points: 16,
  },
  {
    id: 17,
    team_name: "Merle",
    matches_played: 17,
    wins: 17,
    finishes: 17,
    bonus_finishes: 17,
    finish_points: 17,
    position: 17,
    position_points: 17,
  },
  {
    id: 18,
    team_name: "Zabrina",
    matches_played: 18,
    wins: 18,
    finishes: 18,
    bonus_finishes: 18,
    finish_points: 18,
    position: 18,
    position_points: 18,
  },
  {
    id: 19,
    team_name: "Clevie",
    matches_played: 19,
    wins: 19,
    finishes: 19,
    bonus_finishes: 19,
    finish_points: 19,
    position: 19,
    position_points: 19,
  },
  {
    id: 20,
    team_name: "Anderea",
    matches_played: 20,
    wins: 20,
    finishes: 20,
    bonus_finishes: 20,
    finish_points: 20,
    position: 20,
    position_points: 20,
  },
  {
    id: 21,
    team_name: "Rafa",
    matches_played: 21,
    wins: 21,
    finishes: 21,
    bonus_finishes: 21,
    finish_points: 21,
    position: 21,
    position_points: 21,
  },
  {
    id: 22,
    team_name: "Ardyce",
    matches_played: 22,
    wins: 22,
    finishes: 22,
    bonus_finishes: 22,
    finish_points: 22,
    position: 22,
    position_points: 22,
  },
  {
    id: 23,
    team_name: "Shelbi",
    matches_played: 23,
    wins: 23,
    finishes: 23,
    bonus_finishes: 23,
    finish_points: 23,
    position: 23,
    position_points: 23,
  },
  {
    id: 24,
    team_name: "Jolee",
    matches_played: 24,
    wins: 24,
    finishes: 24,
    bonus_finishes: 24,
    finish_points: 24,
    position: 24,
    position_points: 24,
  },
];
